# PVC using hostpath with provisoner
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-hostpath-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
