apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: demo
        name: demo
        imagePullPolicy: Never
        resources: {}
        env:
          - name: TZ
            value: Asia/Tokyo

status: {}