services:
  trino:
    image: 'trinodb/trino:latest'
    ports:
      - '8080:8080'
    volumes:
      - ${PWD}/catalog:/etc/trino/catalog
      - ${PWD}/access-control.properties:/etc/trino/access-control.properties
      - ${PWD}/rules.json:/etc/trino/rules.json
