image:
  tag: "451"
server:
  workers: 3
coordinator:
  jvm:
    maxHeapSize: "8G"
worker:
  jvm:
    maxHeapSize: "8G"

additionalCatalogs:
  bmdb: |-
    connector.name=postgresql
    connection-url=jdbc:postgresql://host.docker.internal:5432/bmdb
    connection-user=postgres
    connection-password=postgres
  wfdb: |-
    connector.name=postgresql
    connection-url=jdbc:postgresql://host.docker.internal:5432/wfdb
    connection-user=postgres
    connection-password=postgres

accessControl:
  type: configmap
  refreshPeriod: 60s
  # Rules file is mounted to /etc/trino/access-control
  configFile: "rules.json"
  rules:
    rules.json: |-
      {
        "tables": [
          {
            "user": "kondoh",
            "catalog": "wfdb",
            "schema": "wf",
            "table": "task_master",
            "privileges": []
          },
          {
            "user": "kondoh",
            "catalog": "wfdb",
            "schema": "wf",
            "table": "flow_master",
            "privileges": ["SELECT"],
            "columns": [
              {
                "name": "flow_property_set_id",
                "allow": false
              },
              {
                "name": "activation_ts",
                "allow": false
              }
            ]
          }
        ]
      }
