apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodejs-api
  name: nodejs-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-api
    spec:
      containers:
      - image: ghcr.io/kondoumh/gh-container-registry/nodejs-server:latest
        name: nodejs-server
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 3000
      imagePullSecrets:
      - name: regcred
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-service
  name: nodejs-service
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nodejs-api
  type: ClusterIP
status:
  loadBalancer: {}
