name: "Test debezium"
on: [workflow_dispatch]

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: minikube start --memory=4096
      - name: Create namespace
        run: kubectl create namespace wf
      - name: Install PostgreSQL
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm install wf-db bitnami/postgresql -f postgres/values.yaml -n wf
      - name: Install kafka
        run: |
          helm install wf-kafka-cluster bitnami/kafka -n wf
      - name: Wait 1
        run: sleep 60
      - name: Install debezium connect for PostgreSQL
        run: |
          kubectl apply -f debezium/kafka-connect-deploy.yaml -n wf
      - name: Install kafka client
        run: kubectl run wf-kafka-client --restart='Never' --image docker.io/bitnami/kafka:2.8.0-debian-10-r0 -n wf --command -- sleep infinity
      - name: Wait 2
        run: sleep 120
      - name: Check
        run: |
          kubectl get po,deploy,svc -n wf
      - name: Execute DDL / DML
        run: |
          kubectl -n wf exec -i wf-db-postgresql-0 -- bash << 'EOC'
            PGPASSWORD=postgres psql -U postgres -c 'create database hoge;'
            PGPASSWORD=postgres psql -U postgres -d hoge -c 'create table account(id varchar(8), name varchar(8));'
            PGPASSWORD=postgres psql -U postgres -d hoge -c "insert into account (id, name) values ('1000', 'Bob');"
          EOC
      - name: Register connector setting
        run: |
          POD=$(kubectl -n wf get pod -l app=kafkaconnect -o jsonpath="{.items[0].metadata.name}")
          kubectl -n wf cp debezium/register-postgres-k8s.json $POD:/kafka/connect/register-postgres-k8s.json
          kubectl -n wf exec -i $POD -- bash << 'EOC'
            IP=$(hostname -i)
            curl -i -X POST -H "Accept:application/json" -H  "Content-Type:application/json" http://$IP:8083/connectors -d @/kafka/connect/register-postgres-k8s.json
          EOC
          kubectl -n wf exec -i $POD -- bash << 'EOC'
            IP=$(hostname -i)
            curl http://$IP:8083/connectors
          EOC
      - name: Check topic
        run: |
          kubectl -n wf exec -i wf-kafka-client -- bash << 'EOC'
            kafka-topics.sh --list --zookeeper wf-kafka-cluster-zookeeper:2181
          EOC
      - name: Consume topic
        run: |
          kubectl -n wf exec -i wf-kafka-client -- bash << 'EOC'
            kafka-console-consumer.sh \
              --bootstrap-server wf-kafka-cluster:9092 \
              --topic postgres.public.account \
              --from-beginning > /bitnami/kafka/consumer.txt &
            sleep 5
            cat /bitnami/kafka/consumer.txt
          EOC
