name: "Test debezium"
on: [workflow_dispatch]

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: minikube start --memory=4096
      - name: Create namespace
        run: kubectl create namespace wf
      - name: Install PostgreSQL
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm install wf-db bitnami/postgresql -f postgres/values.yaml -n wf
          # kubectl wait pod/wf-db-postgresql-0 --for=condition=Ready --timeout=60s -n wf
      - name: Install kafka
        run: |
          helm install wf-kafka-cluster bitnami/kafka -n wf
          # kubectl wait po/wf-kafka-cluster-0 --for=condition=Ready --timeout=60s -n wf
          wait 60
      - name: Install debezium connect for PostgreSQL
        run: |
          kubectl apply -f debezium/kafka-connect-deploy.yaml -n wf
          # kubectl wait deploy/kafkaconnect-deploy --for=condition=Available --timeout=60s -n wf
      - name: Wait
        run: sleep 120
      - name: Check
        run: |
          kubectl get po,deploy,svc -n wf
      - name: Create db and insert data
        run: |
          echo create db
      - name: Register connector setting
        run: |
          POD=$(kubectl -n wf get pod -l app=kafkaconnect -o jsonpath="{.items[0].metadata.name}")
          echo $POD
          kubectl -n wf cp debezium/register-postgres-k8s.json $POD:/kafka/connect/register-postgres-k8s.json
          kubectl -n wf exec -i $POD -- bash << 'EOC'
            ls -l /kafka/connect
          EOC

          # kubectl -n wf exec -i $POD -- bash << 'EOC'
          #   curl -i -X POST -H "Accept:application/json" -H  "Content-Type:application/json" http://kafkaconnect-service:8083/connectors -d @/kafka/connect/register-postgres-k8s.json
          # EOC
          kubectl -n wf exec -i $POD -- bash << 'EOC'
            curl http://kafkaconnect-service:8083/connectors
          EOC
