name: "Test debezium"
on: [workflow_dispatch]

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
      - name: Create namespace
        run: kubectl create namespace wf
      - name: Install PostgreSQL
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm install wf-db bitnami/postgresql -f postgres/values.yaml -n wf
          kubectl run wf-db-postgresql-client --rm --tty -i --restart='Never' --namespace wf --image docker.io/bitnami/postgresql:11.12.0-debian-10-r0 --env="PGPASSWORD=postgres" --command -- psql --host wf-db-postgresql -U postgres -d postgres -p 5432
      - name: Install kafka
        run: helm install wf-kafka-cluster bitnami/kafka -n wf
      - name: Install debezium connect for PostgreSQL
        run: kubectl apply -f debezium/kafka-connect-deploy.yaml
      - name: Check
        run: kubectl get po,svc -n wf
  