name: "Build Debezium postgresql connector images"
on: [workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push container image
        run: |
          cd strimzi
          curl https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/1.7.1.Final/debezium-connector-postgres-1.7.1.Final-plugin.tar.gz | tar xvz
          docker build . -t strimzi-debezium-connect-pgsql
          docker tag strimzi-debezium-connect-pgsql ghcr.io/kondoumh/strimzi-debezium-connect-pgsql:latest
          docker push  ghcr.io/kondoumh/strimzi-debezium-connect-pgsql:latest
