name: Build & Deploy for given tareget

on:
  workflow_call:
    inputs:
      target:
        description: 'Target to deploy app'
        required: true
        type: string

env:
  TARGET: ${{ inputs.target }}

jobs:

  Build:
    uses: kondoumh/iac-dev/.github/workflows/build-reusable.yml@master
    with:
      target: $TARGET

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Deploy
        run: echo "Deploy to $TARGET environment"
