on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
      use-emoji:
        type: boolean
        description: Include emojis


jobs:
  printInputs:
    runs-on: ubuntu-latest
    env:
      USE_EMOJI: ${{ inputs.use-emoji }}
    steps:
    - name: Echo inputs
      run: |
        echo "Log level: ${{ inputs.logLevel }}"
        echo "Tags: ${{ inputs.tags }}" 
        echo "Use emojis: ${{ env.USE_EMOJI }}"
    - name: Echo emoji
      if: ${{ env.USE_EMOJI == 'true' }}
      run: echo "🚀🚀🚀"
