on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
      use-emoji:
        type: boolean
        description: Include emojis

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: Echo inputs
    - run: |
        echo "Log level: ${{ inputs.logLevel }}"
        echo "Tags: ${{ inputs.tags }}" 
        echo "Use emojis: ${{ inputs.use-emoji }}"
    - name: Echo emoji
      if: ${{ (inputs.use-emoji) }}
      run: echo 🚀🚀🚀
