name: Self-hosted runner job

on: [workflow_dispatch]

jobs:
  Build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, self-hosted]

    steps:
    - run: echo 'This job is running on ${{ matrix.runner }} runner!!'
