on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: GitHubSecurityLab/actions-permissions/monitor@v1
    - uses: actions/checkout@master
    - name: Create artifact
      run: echo hello > hello.txt
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: hello-${{ github.run_number }}
        path: ./hello.txt
