name: "Test sandbox action"
on: [workflow_dispatch]

jobs:
  call_sandbox_action:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: sandbox action
      id: hello
      uses: kondoumh/sandbox-action@master
      with:
        who-to-greet: 'Mona the Octocat'
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    - name: sandbox docker action
      id: hello2
      uses: kondoumh/sandbox-container-action@master
      with:
        who-to-greet: 'Mona the Octocat'
    - name: Get the output time
      run: echo "The time was ${{ steps.hello2.outputs.time }}"
