name: Use helmfile
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup helmfile
      uses: mamezou-tech/setup-helmfile@v1.1.0
      with:
        helmfile-version: "v0.148.1"
        helm-version: "v3.10.2"
        kubectl-version: "1.24.7"
        kubectl-release-date: "2022-10-31"

    - name: Test
      run: |
        kubectl version --client
        helmfile --version
        helm version
        helm plugin list
