name: Use helmfile
on: [workflow_dispach]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup helmfile
      uses: mamezou-tech/setup-helmfile@v1
    - name: Test
      run: |
        helmfile --version
        helm version
        kubectl version --client